# Generated by Django 4.1.3 on 2023-02-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='PRICE',
            new_name='PRIZE',
        ),
    ]
