# Generated by Django 4.1.3 on 2023-02-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0004_rename_price_productdb_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='PRIZE',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
