# Generated by Django 4.1.3 on 2023-02-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0009_cartdb_tprize'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('USERNAME', models.CharField(blank=True, max_length=50, null=True)),
                ('ADDRESS', models.CharField(blank=True, max_length=100, null=True)),
                ('STATE', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
