# Generated by Django 4.1.3 on 2023-02-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0010_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='PNAME',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
