# Generated by Django 4.1.3 on 2023-02-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0011_userdetails_pname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='PNAME',
            new_name='EMAIL',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='USERNAME',
        ),
    ]
