# Generated by Django 4.1.3 on 2023-02-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0012_rename_pname_userdetails_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='PRIZE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='PRODUCT',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
